// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUrI9yj6YsYs82M0QF_KlwqLL8nXf5_k4',
    appId: '1:114372126413:web:2e1680af9a8d751e972b84',
    messagingSenderId: '114372126413',
    projectId: 'sonant-c81f1',
    authDomain: 'sonant-c81f1.firebaseapp.com',
    storageBucket: 'sonant-c81f1.firebasestorage.app',
    measurementId: 'G-ZQZD52Y0LE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArIpw3KyH8BBZ-QTjJrPvXnUcomycJUjU',
    appId: '1:114372126413:android:90850ae22b63e290972b84',
    messagingSenderId: '114372126413',
    projectId: 'sonant-c81f1',
    storageBucket: 'sonant-c81f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4nHR1GkWFzIZD1pjuS40OfIBDGTUkHG4',
    appId: '1:114372126413:ios:ea4cab25c91a5852972b84',
    messagingSenderId: '114372126413',
    projectId: 'sonant-c81f1',
    storageBucket: 'sonant-c81f1.firebasestorage.app',
    iosBundleId: 'com.example.sonant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4nHR1GkWFzIZD1pjuS40OfIBDGTUkHG4',
    appId: '1:114372126413:ios:ea4cab25c91a5852972b84',
    messagingSenderId: '114372126413',
    projectId: 'sonant-c81f1',
    storageBucket: 'sonant-c81f1.firebasestorage.app',
    iosBundleId: 'com.example.sonant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUrI9yj6YsYs82M0QF_KlwqLL8nXf5_k4',
    appId: '1:114372126413:web:7436c64f5e795ef1972b84',
    messagingSenderId: '114372126413',
    projectId: 'sonant-c81f1',
    authDomain: 'sonant-c81f1.firebaseapp.com',
    storageBucket: 'sonant-c81f1.firebasestorage.app',
    measurementId: 'G-PV1Q98WGS7',
  );
}
